### ISSUE TITLE
tokenizing of comment, cdata content error

### ISSUE THREAD

**Issue by aptxx** [lezer-parser/xml#4]
hello,

it seems there is a issue in the **tokens.js scanTo**

if there is a character same with the end tag token, the end tag is not detected.
case1: "]" before CDATA end tag "]]>"
case2: "-" before comment end tag "-->"

```
export const commentContent = scanTo(_commentContent, "-->")
export const piContent = scanTo(_piContent, "?>")
export const cdataContent = scanTo(_cdataContent, "]]>")
```

<img width="1406" alt="WeChat94b45144f3fb76a4e9397debb5d6e572" src="https://github.com/lezer-parser/xml/assets/2224883/f5624d80-3ca8-4c93-b717-e1b8744cef01">

**Comment by marijnh** [comment]
Thanks for spotting that. Attached patch should help.

**Comment by aptxx** [comment]
that's cool. it's fixed
