### ISSUE TITLE
Why define a `hash` function when `strict: false`?

### ISSUE THREAD

**Issue by AlexErrant** [lezer-parser/xml#6]
https://github.com/lezer-parser/xml/blob/331ab3dd94446f3b2594e71e8ff68be57c2e33a4/src/tokens.js#L51-L52

[The `hash` documentation](https://lezer.codemirror.net/docs/ref/#lr.ContextTracker.constructor^spec.hash) states:

> Only needed for strict contexts.

Since we're _not_ in a strict context, why define a `hash` function?

**Comment by marijnh** [comment]
That seems to be leftover and indeed, entirely unused. Attached patches remove it.
